### ISSUE TITLE
(Feature)Link Copy option to clipboard

### ISSUE THREAD

**Issue by PIYUSH-69** [PIYUSH-69/SCANNER-APP#1]
The scanned link cant be opened or copied to the clipboard.Add a button to open the link on the browser or to copy to the clipboard

**Comment by krishnachaitanya0107** [comment]
Hi , 

Could you please assign the issue to me , i would like to work on this .

Thanks

**Comment by krishnachaitanya0107** [comment]
Hi @PIYUSH-69  , 

Could you please review/merge the pull request regarding the changes .

Thanks

**Comment by PIYUSH-69** [comment]
@krishnachaitanya0107 Amazing work . I will review and merge it today itself. Don't worry
